<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DisplayHost.aspx.cs" Inherits="FunnyTest.DisplayHost" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table>
                <tr>
                    <td></td>
                    <td>
                        <img alt="" id="imgUp" src="images/up2.png" /></td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <img alt="" id="imgLeft" src="images/left2.png" /></td>
                    <td></td>
                    <td>
                        <img alt="" id="imgRight" src="images/right2.png" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <img alt="" id="imgDown" src="images/down2.png" /></td>
                    <td></td>
                </tr>
            </table>
            <table>
                <tr>
                    <td>
                        <a id="linkGo">
                            <img alt="" id="imgQrCode" src="" />
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    </form>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-2.1.0.min.js"></script>
    <script src="Scripts/jquery-2.1.0.intellisense.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.0.3.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>

    <script type="text/javascript">


        $(function () {


            $("#imgUp").css("visibility", "hidden");
            $("#imgDown").css("visibility", "hidden");
            $("#imgLeft").css("visibility", "hidden");
            $("#imgRight").css("visibility", "hidden");


            var fHub = $.connection.FunnyHub;
            //依據指令來改變圖片的顯示
            fHub.client.changeDirecttoHost = function (direct) {

                $("#imgUp").css("visibility", "hidden");
                $("#imgDown").css("visibility", "hidden");
                $("#imgLeft").css("visibility", "hidden");
                $("#imgRight").css("visibility", "hidden");

                $("#img" + direct).css("visibility", "display");
            };

            //進行斷線
            fHub.client.closeConnection = function () {
                $.connection.hub.stop();
            };


            //已經斷線
            $.connection.hub.disconnected(function () {
                document.title = "失去連線";
                alert("已失去連線！！！");
            });

            //開啟連線
            $.connection.hub.start().done(function () {

                var gid = "<%=Guid.NewGuid() %>";
                //var gid = "host";
                $("#hId").val("host_" + gid);
                var uri = "<%=getUrl()%>QrPic.ashx" + gid;
                $("#imgQrCode").attr("src", uri);
                $("#linkGo").attr("href", "<%=getUrl()%>OperatorClient.aspx?strId=" + gid);
                fHub.server.UserConnected("host_" + gid);

            });

        });

    </script>

</body>
</html>
